config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :sections
  has_many :enrollments
  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  mount_uploader :video, VideoUploader
  belongs_to :section
  include RankedModel
  ranks :row_order, with_same: :section_id
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons
  include RankedModel
  ranks :row_order, with_same: :course_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def enrolled_in?(course)
    # Enrollment.find_by_course_id_and_user_id(course.id, self.id).valid? rescue false
    enrolled_courses.include?(course)
  end

  private

  def all_enrolled
    Enrollment.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!
  def create
    unless current_course.free?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })

      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: "Enrollment in '#{current_course.title}'",
        currency: 'usd',
      })
    end

    enrollment = current_user.enrollments.create(course: current_course)
    if enrollment.valid?
      redirect_to course_path(current_course)
    else
      flash[:error] = "Unable to enroll #{current_user.email} in '#{current_course.title}'"
      redirect_to root_path
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_user, only: [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def render_eperm
    render plain: "Unauthorized", status: :Unauthorized
  end

  def require_authorized_user
    render_eperm unless current_course.user == current_user
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_user, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]
  skip_before_action :verify_authenticity_token, only: [:update]

  def create
    @lesson = current_section.lessons.create(lesson_params)
    if @lesson.valid?
      redirect_to instructor_course_path(current_section.course)
    else
      render :new, :unprocessable_entity
    end
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated'
  end

  private

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end

  def render_eperm
    render plain: "Unauthorized", status: :Unauthorized
  end

  def require_authorized_user
    render_eperm unless current_section.course.user == current_user
  end

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render plain: 'Not authorized', status: :unauthorized
    end
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_user, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]
  skip_before_action :verify_authenticity_token, only: [:update]

  def create
    @section = current_course.sections.create(section_params)
    if @section.valid?
      redirect_to instructor_course_path(current_course)
    else
      render :new, :unprocessable_entity
    end
  end

  def update
    current_section.update_attributes(section_params)
    render plain: 'updated'
  end

  private

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end

  helper_method :current_course
  def current_course
    if params[:course_id]
      @current_course ||= Course.find(params[:course_id])
    else
      current_section.course
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def render_eperm
    render plain: "Unauthorized", status: :Unauthorized
  end

  def require_authorized_user
    render_eperm unless current_course.user == current_user
  end

  def require_authorized_for_current_section
    render plain: 'Not authorized', status: :unauthorized unless current_section.course.user == current_user
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_user

  def show
  end

  private

  helper_method :current_course
  def current_course
    @current_course ||= current_lesson.section.course rescue nil
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_user
    redirect_to(course_path(current_course), alert: "You must enroll in this course to view its lesson details.") unless current_user.enrolled_in?(current_course)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h2 class="text-center">Advance your skill level</h2>
  <br />
  <div class="row">
    <% @courses.each do |c| %>
      <div class="booyah-box col-10 offset-1">
        <div class="row">
          <h5 class="col-10">
            <%= link_to c.title, course_path(c) %>
          </h5  >
        </div>

        <% if c.image && c.image.file %>
          <%= image_tag(c.image.url, class: 'img-fluid') %>
        <% end %>

        <div class="col-sm-8 col-12">
          <%= c.description %>
        </div>
        <br />
        <div class="text-right right-offset-1">
          <%= link_to 'Details', course_path(c), class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <% if @course.image && @course.image.file %>
    <%= image_tag(@course.image.url, class: 'img-fluid') %>
  <% end %>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <%= number_to_currency(@course.cost) %>
      </span>

      <br />
      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
        <br />
        <br />
      <% end %>

      <br />
      <% if current_user %>
        <% if current_user.enrolled_in?(@course) %>
          <h3 class='badge badge-info'>You are enrolled</h3>
        <% else %>
          <% if @course.free? %>
            <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
          <% else %>
            <%= form_tag course_enrollments_path(@course) do %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="Enrollment in '<%= @course.title %>'"
                      data-amount="<%= (@course.cost * 100).to_i %>"
                      data-email="<%= current_user.email %>"
                      data-locale="auto"></script>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <h3 class='badge badge-info'>Sign in to enroll</h3>
      <% end %>
      <br />
      <br />
    </div>
  </div>
  <div class="col-sm-8 col-12">
    <%= @course.description %>
  </div>

  <div class="col-12">
    <% @course.sections.rank(:row_order).each do |s| %>
      <br /><br />
      <div class="section">
        <h3><%= s.title %></h3>
        <div class="row">
          <% s.lessons.rank(:row_order).each do |l| %>
            <div class="col-12 col-sm-6">
              <div class="lesson text-center">
                <br />
                <%= link_to lesson_path(l) do %>
                  <b><%= l.title %></b>
                  <br />
                  <%= l.subtitle %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <br class="clr" />
      </div>
    <% end %>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a course</h1>
  <%= simple_form_for(@course, url: instructor_courses_path) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.new-lesson-button').click(function() {
      var lessonUrl = $(event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    })

    $('.lessons').sortable({
      update: function(event, ui) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() }}
        });
      }
    });
  });

  $(function() {
    $('.sections').sortable({
      update: function(event, ui) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() }}
        });
      }
    });
  });
</script>

<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <% if current_course.image && current_course.image.file %>
    <%= image_tag(current_course.image.url, class: 'img-fluid') %>
  <% end %>
  <br />

  <%= link_to 'Preview as student', course_path(current_course), class: 'btn btn-warning' %>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newSection">
    New Section
  </button>
  
  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |s| %>
      <li data-update-url="<%= instructor_section_path(s) %>" class="section-li">
        <div class="header">
          <span class="fa fa-ellipsis-v"></span>
          <%= s.title %>
        </div>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary float-right new-lesson-button" data-toggle="modal" data-target="#newLesson" data-lesson-url="<%= instructor_section_lessons_path(s) %>">
          New Lesson
        </button>
        <br class="clr" />
        <br class="clr" />
        <ul class="lessons">
          <% s.lessons.rank(:row_order).each do |l| %>
            <li data-update-url=<%= instructor_lesson_path(l) %>>
              <div class="row">
                <div class="col-1">
                  <br />
                  <span class="fa fa-ellipsis-v"></span>
                </div>
                <div class="col-11 text-center">
                  <p>
                    <b><%= l.title %></b>
                  </p>
                  <p>
                    <%= l.subtitle %>
                  </p>
                </div>
              </div>
              <br class="clr" />
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>
</div>

<!-- New Section Modal -->
<div class="modal fade" id="newSection" tabindex="-1" role="dialog" aria-labelledby="newSectionLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newSectionLabel">Create a Section</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for(@section, url: instructor_course_sections_path(current_course)) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit 'Save', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- New Lesson Modal -->
<div class="modal fade" id="newLesson" tabindex="-1" role="dialog" aria-labelledby="newLessonLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newLessonLabel">Create a Lesson</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for(@lesson, url: '#', html: {id: 'newLessonForm'}) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit 'Save', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p><%= current_lesson.subtitle %></p>
  <video
    id="my-video"
    class="video-js vjs-big-play-centered vjs-default-skin vjs-fluid"
    controls
    preload="auto"
    poster="<%= image_path('black.jpg') %>"
    data-setup='{}'
  >
    <source src="<%= current_lesson.video.to_s %>" type="video/mp4" />
    <noscript>
      <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a
        web browser that
        <a href="https://videojs.com/html5-video-support/" target="_blank"
          >supports HTML5 video</a
        >
      </p>
    </noscript>
  </video>
</div>